language: node_js
sudo: required
node_js:
  - "4.2"
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
install:
  - npm install
script: npm run test-ci
cache:
  directories:
    - node_modules
